name: Deploy WordPress to Hodi

# Trigger on merges (or any push) to master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Set up the SSH key
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 3) SSH in and pull the latest master
      - name: Deploy via SSH
        run: |
          ssh -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd ${{ secrets.TARGET_DIR }} && \
            git pull origin master && \
            wp db import db/local.sql && \
            wp search-replace 'https://manateam-wp.ddev.site' 'https://manateam.maurice.webcup.hodi.host' --all-tables && \
            wp elementor replace_urls 'https://manateam-wp.ddev.site' 'https://manateam.maurice.webcup.hodi.host' && \
            wp elementor flush_css && \
            wp cache flush"

      # ── ❶ Capture last commit title ─────────────────────────────
      - name: Get last commit title
        id: last-commit
        run: |
          # %s is subject (first line) of the commit
          echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      # ── ❷ Notify Slack on Success (with commit) ─────────────────
      - name: Slack → Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload=$(
            jq -n \
              --arg text    "✅ Deployment to *WordPress* succeeded!" \
              --arg commit  "${{ steps.last-commit.outputs.message }}" \
              '{ text: ($text + "\n> *" + $commit + "*") }'
          )
          curl -X POST -H 'Content-type: application/json' \
               --data "$payload" \
               "$SLACK_WEBHOOK_URL"

      # ── ❸ Notify Slack on Failure (with commit) ─────────────────
      - name: Slack → Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload=$(
            jq -n \
              --arg text   "❌ Deployment to *WordPress* FAILED!" \
              --arg commit "${{ steps.last-commit.outputs.message }}" \
              '{ text: ($text + "\n> *" + $commit + "*\nCheck Actions logs for details.") }'
          )
          curl -X POST -H 'Content-type: application/json' \
               --data "$payload" \
               "$SLACK_WEBHOOK_URL"