name: Deploy WordPress to Hodi

# Trigger on merges (or any push) to master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Set up the SSH key
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 3) SSH in and pull the latest master
      - name: Deploy via SSH
        run: |
          ssh -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd ${{ secrets.TARGET_DIR }} && \
            git pull origin master && \
            composer install --no-dev --optimize-autoloader && \
            wp cache flush"

      # ── Notify Slack on Success ──
      - name: Slack → Success
        if:   ${{ success() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload='{ "text": "✅ Deployment to *WordPress* SF site succeeded!" }'
          curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            "$SLACK_WEBHOOK_URL"

      # ── Notify Slack on Failure ───
      - name: Slack → Failure
        if:   ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload='{ "text": "❌ Deployment to *WordPress* site failed. Check the Actions log." }'
          curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            "$SLACK_WEBHOOK_URL"